version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket infratests3 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml